### ISSUE TITLE
Compiling wasm to native fails because of `ReservedReg` being unimplemented

### ISSUE THREAD

**Issue by Vurich** [cretonne/cretonne#205]
`cton-util wasm --isa intel some-file.wasm` fails when legalising because `DummyFuncEnvironment::make_heap` emits a heap with `ReservedReg` but `offset_addr` is unimplemented for `ReservedReg`. I tried making it an empty implementation but that leads to an infinite loop (as you'd expect), and the only other thing I can think of is replacing it with an offset from `vmctx`, but there's no clear way to emit that (I can't explore the documentation easily since there's a lot of generated code). I can compile to `cton` with `cton-util wasm -pc some-file.wasm` and it appears to produce sensible code.

There is no documentation anywhere (not in the code or on http://cretonne.readthedocs.io/) that documents precisely what `reserved_reg` is supposed to represent, I'm just inferring what I can from reading the code, tests and examples.

**Comment by stoklund** [comment]
Cc @sunfishcode

**Comment by sunfishcode** [comment]
I believe the intention of [ReservedReg](https://github.com/stoklund/cretonne/blob/57775b18beb8b9273cf983bf78758edbc2705095/lib/cretonne/src/ir/heap.rs#L27) is that codegen should reserve a register globally, and use it for register allocation, so that it's always available for heap computations. However, that's indeed not implemented in codegen yet.

[wasmstandalone](https://github.com/sunfishcode/wasmstandalone) has an [implementation](https://github.com/sunfishcode/wasmstandalone/blob/29db33e7f8cdb0ed1c63400911fef187408a2992/lib/runtime/src/lib.rs#L246) of `FuncEnvironment` which uses a `GlobalVar` base instead, which is implemented. wasmstandalone is more complete than the `DummyEnvironment`, though it is not fully complete yet. I'm happy to help or answer any questions about either.

**Comment by Vurich** [comment]
Ok, so I had guessed that `ReservedReg` was, as you say, a reserved register that's specific to codegen, but if you try to pass it through to the specific ISA (i.e. do nothing in `offset_addr`) it hits an infinite loop, implying that the heap-based instructions are just macros that are not in the minimal instruction set. I don't know which bit is actually causing the infinite loop, can you shed some light on that?

**Comment by stoklund** [comment]
The legalizer's `offset_addr()` function is supposed to replace the `heap_addr` instruction with a code sequence that computes the  heap base address. As you have found, this is not yet implemented for the reserved register option.

If the legalizer doesn't do its job of replacing the `heap_addr` instruction, then it will indeed cause an infinite loop.

Do you actually need the reserved register heap?

Heaps with a base address in a global variable relative to `vmctx` do work. Getting reserved register heaps to work is not a one-line fix. It is fairly complicated.

**Comment by sunfishcode** [comment]
Yes, abstract instructions like `heap_addr` are effectively like macros, in that they are expanded during the legalizer phase. The legalizer is responsible for lowering all the way down to target-machine opcodes, and it's iterative, so each step needs to replace its input with something lower-level, in order to continue to make progress and eventually terminate.

**Comment by Vurich** [comment]
Right, I was under the impression that the legaliser just converted to a minimal subset of cretonne. So, in order to implement the reserved register heap would you have to query the target ISA for the target op sequence? Assumably, you would have to fail if the target ISA didn't support it. I'll have a look at `wasmstandalone`, though, that seems like it's more what I need.

**Comment by sunfishcode** [comment]
Yeah; for example, this might be similar to the `copy_special` instruction being added [here](https://github.com/stoklund/cretonne/pull/201) for copying between registers.

**Comment by Vurich** [comment]
I'm not sure which bit I'm supposed to be looking at, can you link me to the line where they query the ISA?

**Comment by sunfishcode** [comment]
`copy_special` is defined [here](https://github.com/stoklund/cretonne/pull/201/files#diff-5c05591943fa8fe4054287c67216beafR540) as a base instruction, which then is given an x86 encoding [here](https://github.com/stoklund/cretonne/pull/201/files#diff-b3758d42a077977cd14c449fc98b035aR237). Currently only x86 is implemented, though other ISAs would be able to define their own encodings in a similar manner.

**Comment by stoklund** [comment]
I've changed the dummy environment to use a `vmctx`-based heap instead of a reserved register.

**Comment by Vurich** [comment]
It seems like `vmctx` is only used as a pointer to the heap right now, but the documentation implies that it's supposed to point to a structure with information about the host. How does that work w.r.t. compiling for both VMs and native code? Surely if you use it like a heap then you could overwrite the host datastructure by accident, but if you use it as a structure then you'll read uninit on native targets?

**Comment by sunfishcode** [comment]
@Vurich The `vmctx` isn't meant to point to the heap directly, but to a data structure which contains a pointer to the heap. The `GlobalVar` is the pointer to the heap, and the `vmctxt` plus offset is how to load it.

**Comment by sunfishcode** [comment]
The documentation now mentions that `reserved_reg` is not yet implemented. And the dummy environment now uses a `vmctx`-based heap. If there are further questions, please reopen or file new issues!
