### ISSUE TITLE
Segfault from emscripten binaryen0.test_atomic_cxx

### ISSUE THREAD

**Issue by kripken** [Cretonne/cretonne#251]
This is a reduced testcase, which now hangs without cretonne (the correct behavior) but crashes with `--wasm-always-cretonne`.

[src.cpp.o.js.gz](https://github.com/Cretonne/cretonne/files/1773336/src.cpp.o.js.gz)
[src.cpp.o.wasm.gz](https://github.com/Cretonne/cretonne/files/1773337/src.cpp.o.wasm.gz)

**Comment by sunfishcode** [comment]
When built in debug mode, Spidermonkey emits extra sanity checks in various places, and one of those checks caught the problem here. Spidermonkey expects functions returning i32 to zero the high 32 bits of the 64-bit register, while Cretonne wasn't aware of that requirement and was leaving garbage in those bits. I've now fixed this with a patch to baldrdash to explicitly declare the requirement that the return register bits be zeroed.
