### ISSUE TITLE
Amortize determining heap base address

### ISSUE THREAD

**Issue by pchickey** [cretonne/cretonne#278]
We are using the `heap_addr` instruction to access the heap. Currently, one of our big performance bottlenecks is the repeated calculation (by dereferencing a pointer) of the heap base address. We are seeking to amortize this calculation to once per function.

The heap addr legalization expands the base address to a deref of the global variable representing the heap here:
https://github.com/cretonne/cretonne/blob/ec21c37c1bf57641879b61dd1fd358a909867ec6/lib/cretonne/src/legalizer/heap.rs#L178

I see two possible approaches to this:

1. I could calculate the base addr once in the initial ebb of a function, and use that value for all subsequent heap_addr instructions. Since I can't modify the way any of the code in the `heap_addr` legalizer works, I would have to lift out code from that legalization pass to my own FunctionEnvironment, so that the base addr calculation can happen in the entry ebb and all subsequent bounds checking is "inlined" at the sites i currently use heap_addr.

2. Make it so that the base addr can be calculated without a deref - in our case, we'd like to change our runtime so that the value of `vmctx` *is* a pointer to the start of the heap, rather than pointing to a structure containing a pointer to the start of the heap. This means I'd need to make it possible to use the value *of* a global ir::HeapBase rather than the value *pointed to* by the global, which would in turn require a way to treat global variables as values rather than pointers, meaning you can't use `global_addr` on globals variables which are values, and need to redesign a fair bit of stuff.

Both of these seem a little bit scary. I could do option 2 but we'd need to discuss the various design tradeoffs about global variables first.

**Comment by sunfishcode** [comment]
A variation on 1 is to modify the legalization pass itself to put the base addresses in the function entry block. I now have a prototype of this here: https://github.com/Cretonne/cretonne/pull/280. At the moment, this will sometimes result in trading a load from a global into a load from a spill slot, because of issues like https://github.com/Cretonne/cretonne/issues/246, but it's a first step.

I agree that 2 is something to consider eventually, because even if we can amortize the cost of the load, it's always going to have some cost.

Another bigger-picture strategy is to introduce some basic aliasing properties for globals. This might look like two flags to start with:
 - ReadOnly - loads with this flag have no memory dependencies
 - MutableGlobal - loads and stores with this flag only depend on other loads and stores with this flag

With those, we could teach `simple_gvn` and `licm` to eliminate redundant loads from globals fairly effectively, which would work for Dynamic as well as Static heaps. And we could use these flags to support rematerialization of loads in the register allocator.

**Comment by pchickey** [comment]
Ok, I was hesitant to implement anything in the legalizer but if you think it is the right place to implement option 1, I'll run with that and send your prototype through our benchmarks to see how much it wins us - I expect its quite a bit

**Comment by sunfishcode** [comment]
As a brief update here, https://github.com/cretonne/cretonne/issues/358 has a design that should make option 2 here possible.

**Comment by lachlansneff** [comment]
@pchickey Once #363 is merged, option 2 will be possible, as Dan said.

**Comment by sunfishcode** [comment]
#363 and #358 are finished now, so we now have one option for reducing the heap base address cost: it's now possible to have the heap base be a simple offset from the vmctx, avoiding any indirection.

The remaining issue here is reducing the redundancy of heap computations that do use indirection, and this is now being tracked in #366. I think in the long term this will be a better approach than simply hoisting everything up to the entry block as #280 does.
