### ISSUE TITLE
Do not hardcode "python" in scripts

### ISSUE THREAD

**Issue by 6A** [cretonne/cretonne#381]
When trying to build `cretonne-codegen`, the command `python` cannot be found (my setup has `python3` and `python3.6`, but not `python` in the PATH) in `lib/codegen/build.rs`. It seems the files `lib/codegen/meta/check.sh` and `test-all.sh` also use hardcoded versions of Python.

I think it would help to use an environment variable such as `PYTHON` or `PY` instead of hardcoding the name `python` everywhere.

**Comment by sunfishcode** [comment]
Is there a standard or conventional way to do this? I'm nervous about making the build sensitive to uncommon environment variables.

The reason we use `python` rather than `python3` is that it's still somewhat common for systems to have python2.7 and not python3 and we're currently compatible with both.

I'll also mention that we'd ideally like to [migrate away from python altogether](#342).

**Comment by 6A** [comment]
AFAIK it's not common, but it could help for the time being. I did end up creating a symlink though, which worked.

**Comment by sunfishcode** [comment]
I just created #386 to attempt to fix this. This makes the build.rs file try "python", "python3", and "python2.7", to find one that works. Would you mind testing this to see if it fixes the issue for you?

**Comment by 6A** [comment]
@sunfishcode It does work for me. I still think a custom command should be useful in case no Python binary is in the path for a reason or another, but I do understand that's a very unlikely scenario.

**Comment by 6A** [comment]
That makes sense, then that's good for me!
